#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-builder
Version  : 3.2.2
Release  : 7
URL      : https://rubygems.org/downloads/builder-3.2.2.gem
Source0  : https://rubygems.org/downloads/builder-3.2.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
# Project: Builder
## Goal
Provide a simple way to create XML markup and data structures.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n builder-3.2.2
gem spec %{SOURCE0} -l --ruby > rubygem-builder.gemspec

%build
gem build rubygem-builder.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
builder-3.2.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/builder-3.2.2
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/builder-3.2.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/doc/jamis.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/doc/releases/builder-1.2.4.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/doc/releases/builder-2.0.0.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/doc/releases/builder-2.1.1.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/blankslate.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/blankslate.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xchar.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlevents.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/lib/builder/xmlmarkup.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/rakelib/publish.rake
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/rakelib/tags.rake
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/performance.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/preload.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/test_blankslate.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/test_eventbuilder.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/test_markupbuilder.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/test_method_caching.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/test_namecollision.rb
/usr/lib64/ruby/gems/2.3.0/gems/builder-3.2.2/test/test_xchar.rb
/usr/lib64/ruby/gems/2.3.0/specifications/builder-3.2.2.gemspec
